apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: metadata-injector
  name: metadata-injector-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metadata-injector-metadata-injector-manager-role
subjects:
  - kind: ServiceAccount
    name: metadata-injector-controller
    namespace: metadata-injector-system
