apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metadata-injector-manager-role
rules:
  - apiGroups:
      - core.k8s.ruso.dev
    resources:
      - metadatainjectors
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core.k8s.ruso.dev
    resources:
      - metadatainjectors/finalizers
    verbs:
      - update
  - apiGroups:
      - core.k8s.ruso.dev
    resources:
      - metadatainjectors/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - get
      - list
      - patch
      - update
      - watch
