apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metadata-injector.fullname" . }}
  {{- if .Values.namespace.name }}
  namespace: {{ include "metadata-injector.namespaceName" . }}
  {{- end }}
  labels:
    {{- include "metadata-injector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "metadata-injector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "metadata-injector.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "metadata-injector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: manager
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --metrics-bind-address=:{{ .Values.metrics.port }}
            - --health-probe-bind-address=:{{ .Values.probe.port }}
            - --leader-elect
          ports:
            - containerPort: {{ .Values.metrics.port }}
              name: https
              protocol: TCP
            - containerPort: {{ .Values.probe.port }}
              name: health
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.probe.port }}
            initialDelaySeconds: {{ .Values.probe.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.probe.port }}
            initialDelaySeconds: {{ .Values.probe.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.readiness.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
