{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "metadata-injector.fullname" . }}-manager-rolebinding
  labels:
    {{- include "metadata-injector.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "metadata-injector.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "metadata-injector.serviceAccountName" . }}
    namespace: {{ include "metadata-injector.namespaceName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "metadata-injector.fullname" . }}-leader-election-rolebinding
  namespace: {{ include "metadata-injector.namespaceName" . }}
  labels:
    {{- include "metadata-injector.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "metadata-injector.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "metadata-injector.serviceAccountName" . }}
    namespace: {{ include "metadata-injector.namespaceName" . }}
{{- end }}
