{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metadata-injector.serviceAccountName" . }}
  {{- if .Values.namespace.name }}
  namespace: {{ include "metadata-injector.namespaceName" . }}
  {{- end }}
  labels:
    {{- include "metadata-injector.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
