apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: operators.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MetadataInjector is the Schema for the metadatainjectors API
      displayName: Metadata Injector
      kind: MetadataInjector
      name: metadatainjectors.core.k8s.ruso.dev
      version: v1alpha1
  description: A Kubernetes operator that automatically injects metadata (labels and
    annotations) into specified resources across your cluster. Supports both labels
    and annotations injection with namespace filtering capabilities and configurable
    reconciliation intervals.
  displayName: Metadata Injector Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - kubernetes
  - k8s
  - operator
  - metadata-injector
  - metadata
  - injector
  - labels
  - annotations
  - management
  - resource-management
  links:
  - name: Operators
    url: https://operators.domain
  maintainers:
  - email: ruslanguns@gmail.com
    name: Ruslan Gonzalez
  maturity: alpha
  provider:
    name: ruso.dev
    url: https://ruso.dev
  version: 0.0.0
