name: Git Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Download Helm artifacts
        uses: actions/download-artifact@v3
        with:
          name: helm-artifacts
          path: release-artifacts

      - name: Generate Release Notes
        run: |
          mkdir -p .artifacthub/release-notes
          VERSION=${VERSION} envsubst < .github/release-template-artifacthub.yml > \
            .artifacthub/release-notes/v${VERSION}.yml

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-artifacts/*.tgz
            .artifacthub/release-notes/v${{ env.VERSION }}.yml
          generate_release_notes: true
          body: |
            📦 Released Helm Chart v${{ env.VERSION }}

            🔗 View installation instructions in our documentation.
