name: Git Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Download Helm artifacts
        uses: actions/download-artifact@v3
        with:
          name: helm-artifacts
          path: release-artifacts

      - name: Generate manifests
        run: |
          make build-installer \
            VERSION=${VERSION} \
            IMG=${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/metadata-injector-operator:v${VERSION}

      - name: Generate CRDs Bundle
        run: |
          mkdir -p release-artifacts/crds
          cp config/crd/bases/* release-artifacts/crds/
          tar -czf release-artifacts/crds.tar.gz -C release-artifacts/crds .
          cp config/crd/bases/* release-artifacts/
          cp dist/install.yaml release-artifacts/

      - name: Generate Release Notes
        run: |
          VERSION=${VERSION} envsubst < .github/release-template.md > release-artifacts/release-notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-artifacts/*.yaml
            release-artifacts/*.tar.gz
            release-artifacts/*.tgz
          body_path: release-artifacts/release-notes.md
          generate_release_notes: true
