name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  verify:
    uses: ./.github/workflows/verify.yml

  docker:
    needs: verify
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit

  helm:
    needs: docker
    uses: ./.github/workflows/helm-build.yml
    secrets: inherit

  git-release:
    needs: [docker, helm]
    uses: ./.github/workflows/git-release.yml
    secrets: inherit
