name: Verify

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "~1.22"

      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "~1.22"

      - name: Running Tests
        run: |
          go mod tidy
          make test
